import os

print("You are a prisoner that has been held captive on a Spaceship for 6 months.\n Now it's your time to escape. A guard that you bribed will come at night time to open your cell.")
print("The guard came and opened your cell, where will you go?")
print("1-Go left")
print("2-Go right")
print("3-Go straight")
option = int(input())
if option < 1 and option > 3:
    while option < 1 and option > 3:
        print("Not valid option. Try again: ")
        option = int(input())
    if option == 1:
        print("You arrive at the door leading to the room where the escape pods are located, but the electronic door is closed.")
        print("What do you do?")
        print("1-Try to hack the door from the control panel next to it.")
        print("2-Wait for someone to open the door.")
        print("3-Go in another direction.")
        option = int(input())
        if option < 1 and option > 3:
            while option < 1 and option > 3:
                print("Not valid option. Try again: ")
                option = int(input())
                if option == 1:
                    os.system("cls")
                    print("You fail to hack the panel and an alarm sounds.")
                    print("What do you do?")
                    print("1-Persist and try to hack the panel before the guards arrive.")
                    print("2-Hide in a hiding spot.")
                    print("3-Run away.")
                    option = int(input())
                    if option < 1 and option > 3:
                        while option < 1 and option > 3:
                            print("Not valid option. Try again: ")
                            option = int(input())
                        if option == 1:
                            os.system("cls")
                            print("You manage to open the door just as the guards arrive, and they are armed!")
                            print("You must choose quickly, which escape pod do you pick?")
                            print("1-The first.")
                            print("2-The second.")
                            print("3-The third.")
                            option = int(input())
                            if option < 1 and option > 3:
                                while option < 1 and option > 3:
                                    print("Not valid option. Try again: ")
                                    option = int(input())
                                if option == 1:
                                    os.system("cls")
                                    print("You went as fast as you could, but you didn't realize that the escape pod was under repair.")
                                    print("As a result, the escape pod doesn't start, and the guards capture you.")
                                    print("-------------")
                                    print("--GAME OVER--")
                                    print("--YOU  LOSE--")
                                    print("-------------")
                                elif option == 2:
                                    os.system("cls")
                                    print("You were fast enough and realized that the first escape pod was under repair.")
                                    print("The second escape pod starts, and you manage to escape.")
                                    print("-------------")
                                    print("--GAME OVER--")
                                    print("---YOU WIN---")
                                    print("-------------")
                                elif option == 3:
                                    os.system("cls")
                                    print("You weren't fast enough, the third capsule was too far away.")
                                    print("One of the guards' shots hits you, and they manage to capture you.")
                                    print("-------------")
                                    print("--GAME OVER--")
                                    print("--YOU  LOSE--")
                                    print("-------------")
                        elif option == 2:
                            os.system("cls")
                            print("A guard opens the door to see if there's anyone.")
                            print("What do you do?")
                            print("1-Run towards the escape pod room.")
                            print("2-Continue hiding.")
                            print("3-Grab a guard as a hostage.")
                            option = int(input())
                            if option < 1 and option > 3:
                                while option < 1 and option > 3:
                                    print("Not valid option. Try again: ")
                                    option = int(input())
                                if option == 1:
                                    os.system("cls")
                                    print("You run as fast as you can, but the guards are faster and capture you.")
                                    print("-------------")
                                    print("--GAME OVER--")
                                    print("--YOU  LOSE--")
                                    print("-------------")
                                elif option == 2:
                                    os.system("cls")
                                    print("You continue hiding, but the guards begin to search the area and eventually find and capture you.")
                                    print("-------------")
                                    print("--GAME OVER--")
                                    print("--YOU  LOSE--")
                                    print("-------------")
                                elif option == 3:
                                    os.system("cls")
                                    print("You wait for the perfect moment to leave your hiding spot and catch a guard off guard.")
                                    print("You use him as a hostage and escape in one of the capsules.")
                                    print("-------------")
                                    print("--GAME OVER--")
                                    print("---YOU WIN---")
                                    print("-------------")
                        elif option == 3:
                            os.system("cls")
                            print("You try to run away, but along the way you encounter some guards who capture you.")
                            print("-------------")
                            print("--GAME OVER--")
                            print("--YOU  LOSE--")
                            print("-------------")
                if option == 2:
                    os.system("cls")
                    print("You've been waiting for a long time, but no one opens the door, although that makes sense, they're escape pods, only used in emergencies.")
                    print("What do you do?")
                    print("1-Continue waiting.")
                    print("2-Go in another direction.")
                    print("3-Trigger an accident.")
                    option = int(input())
                    if option < 1 and option > 3:
                        while option < 1 and option > 3:
                            print("Not valid option. Try again: ")
                            option = int(input())
                        if option == 1:
                            os.system("cls")
                            print("You keep waiting until suddenly an alarm sounds and you hear a voice saying, 'He has escaped.'")
                            print("What do you do?")
                            print("1-Try to hack the door from the control panel next to it.")
                            print("2-Hide in a hiding spot and continue waiting.")
                            print("3-Blend in with the crowd.")
                            option = int(input())
                            if option < 1 and option > 3:
                                while option < 1 and option > 3:
                                    print("Not valid option. Try again: ")
                                    option = int(input())
                                if option == 1:
                                    os.system("cls")
                                    print("You fail to hack the panel, and the guards capture you.")
                                    print("-------------")
                                    print("--GAME OVER--")
                                    print("--YOU  LOSE--")
                                    print("-------------")
                                elif option == 2:
                                    os.system("cls")
                                    print("You continue hiding until they stop searching, and finally, a maintenance worker opens")
                                    print("the door for inspection, allowing you to escape in an escape pod.")
                                    print("-------------")
                                    print("--GAME OVER--")
                                    print("---YOU WIN---")
                                    print("-------------")
                                elif option == 3:
                                    os.system("cls")
                                    print("You blend into the crowd, but since you're wearing prisoner clothes,")
                                    print("the guards quickly identify you and end up capturing you.")
                                    print("-------------")
                                    print("--GAME OVER--")
                                    print("--YOU  LOSE--")
                                    print("-------------")
                        elif option == 2:
                            os.system("cls")
                            print("You go in another direction, but along the way, you encounter some guards who capture you.")
                            print("-------------")
                            print("--GAME OVER--")
                            print("--YOU  LOSE--")
                            print("-------------")
                        elif option == 3:
                            os.system("cls")
                            print("What accident do you think you should provoke?")
                            print("1-Start a fire")
                            print("2-Make a hole in the spaceship wall.")
                            print("3-Trip a waiter.")
                            option = int(input())
                            if option < 1 and option > 3:
                                while option < 1 and option > 3:
                                    print("Not valid option. Try again: ")
                                    option = int(input())
                                if option == 1:
                                    os.system("cls")
                                    print("You provoke a large fire, and even though the ceiling extinguishers quickly put out the fire,")
                                    print("people get scared and head towards the escape pods, opening the door and allowing you to escape in one of them.")
                                    print("-------------")
                                    print("--GAME OVER--")
                                    print("---YOU WIN---")
                                    print("-------------")
                                elif option == 2:
                                    os.system("cls")
                                    print("You head to the engine room and blow up the engine.")
                                    print("That causes a huge hole that sucks you out into outer space.")
                                    print("-------------")
                                    print("--GAME OVER--")
                                    print("--YOU  LOSE--")
                                    print("-------------")
                                elif option == 3:
                                    os.system("cls")
                                    print("Why did you do that, you didn't accomplish anything, you just drew attention and the guards captured you.")
                                    print("-------------")
                                    print("--GAME OVER--")
                                    print("--YOU  LOSE--")
                                    print("-------------")
                if option == 3:
                    os.system("cls")
                    print("You decide to go in another direction.")
                    print("Where will you go?")
                    print("1-Return to the cell.")
                    print("2-Go towards the auxiliary spaceship of the spacship.")
                    print("3-Go to the bridge to talk to the captain.")
                    option = int(input())
                    if option < 1 and option > 3:
                        while option < 1 and option > 3:
                            print("Not valid option. Try again: ")
                            option = int(input())
                        if option == 1:
                            os.system("cls")
                            print("I don't understand why you chose this option, you've locked yourself up again.")
                            print("-------------")
                            print("--GAME OVER--")
                            print("--YOU  LOSE--")
                            print("-------------")
                        elif option == 2:
                            os.system("cls")
                            print("You arrive at the spaceport of the spaceship to board the auxiliary spaceship.")
                            print("What do you do?")
                            print("1-Try to hack the control panel to board the spaceship and escape.")
                            print("2-Convince a pilot that you need them to take you in the spaceship.")
                            print("3-Wait for someone to board the spaceship and sneak aboard as a stowaway.")
                            option = int(input())
                            if option < 1 and option > 3:
                                while option < 1 and option > 3:
                                    print("Not valid option. Try again: ")
                                    option = int(input())
                                if option == 1:
                                    os.system("cls")
                                    print("You manage to hack the control panel and board the spaceship while some guards see you and shoot at you.")
                                    print("Eventually, you manage to escape.")
                                    print("-------------")
                                    print("--GAME OVER--")
                                    print("---YOU WIN---")
                                    print("-------------")
                                elif option == 2:
                                    os.system("cls")
                                    print("The pilot doesn't believe anything you say and realizes you're the prisoner. Then some guards arrive and capture you.")
                                    print("-------------")
                                    print("--GAME OVER--")
                                    print("--YOU  LOSE--")
                                    print("-------------")
                                elif option == 3:
                                    os.system("cls")
                                    print("Time passes, and nobody boards the spaceship until suddenly an alarm sounds, two guards spot you and capture you.")
                                    print("-------------")
                                    print("--GAME OVER--")
                                    print("--YOU  LOSE--")
                                    print("-------------")
                        elif option == 3:
                            os.system("cls")
                            print("You go to the bridge to speak with the captain.")
                            print("What do you say to him?")
                            print("1-Tell him that it's all a mistake and that you shouldn't be imprisoned.")
                            print("2-Confess your deeds and admit you are guilty.")
                            print("3-Tell him that you have a witness who can verify that you are not guilty.")
                            option = int(input())
                            if option < 1 and option > 3:
                                while option < 1 and option > 3:
                                    print("Not valid option. Try again: ")
                                    option = int(input())
                                if option == 1:
                                    os.system("cls")
                                    print("The captain doesn't believe you.")
                                    print("The guards capture you and take you back to the cell.")
                                    print("-------------")
                                    print("--GAME OVER--")
                                    print("--YOU  LOSE--")
                                    print("-------------")
                                elif option == 2:
                                    os.system("cls")
                                    print("You confess your actions, and thanks to that, the guards capture you and take you back to the cell.")
                                    print("-------------")
                                    print("--GAME OVER--")
                                    print("--YOU  LOSE--")
                                    print("-------------")
                                elif option == 3:
                                    os.system("cls")
                                    print("You ask for the guard you had previously bribed to come, and he testifies in your favor, thus securing your release.")
                                    print("-------------")
                                    print("--GAME OVER--")
                                    print("---YOU WIN---")
                                    print("-------------")